services:
  # MySQL 資料庫服務
  mysql:
    image: mysql:8.0
    container_name: paper-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paper_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - paper-network
    command: --authentication-policy=caching_sha2_password

  # Python 爬蟲微服務
  python-crawler:
    build: ./python-crawler
    container_name: paper-management-python-crawler
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    networks:
      - paper-network
    depends_on:
      - mysql
    restart: unless-stopped

  # Spring Boot 應用程式
  springboot-app:
    build: .
    container_name: paper-management-springboot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/paper_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - PYTHON_CRAWLER_URL=http://python-crawler:5000
    networks:
      - paper-network
    depends_on:
      - mysql
      - python-crawler
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  paper-network:
    driver: bridge 